name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  aws-region:  # id of input
    description: 'region'
    required: true
  aws-access-key-id:  # id of input
    description: 'access-key'
    required: true
  aws-secret-access-key:  # id of input
    description: 'secret access key'
    required: true

runs:
  using: 'node16'
  main: 'index.js'